kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
images:
- name: quay.io/coreos/etcd
  newName: cet-docker-virtual.artifactory.swisscom.com/quay.io/coreos/etcd
  newTag: latest
- name: gcr.io/google_containers/kube-apiserver-amd64
  newName: cet-docker-virtual.artifactory.swisscom.com/gcr.io/google_containers/kube-apiserver-amd64
  newTag: v1.7.3
- name: consul
  newName: cet-docker-virtual.artifactory.swisscom.com/consul
  newTag: 1.3.0
- name: gliderlabs/registrator
  newName: cet-docker-virtual.artifactory.swisscom.com/gliderlabs/registrator
  newTag: latest
- name: docker.io/istio/pilot
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/pilot
  newTag: 1.1.4
- name: docker.io/openzipkin/zipkin
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/openzipkin/zipkin
  newTag: "2.7"
- name: galley
  newName: cet-docker-virtual.artifactory.swisscom.com/galley
- name: node-agent-k8s
  newName: cet-docker-virtual.artifactory.swisscom.com/node-agent-k8s
- name: repository
  newName: cet-docker-virtual.artifactory.swisscom.com/repository
- name: mixer
  newName: cet-docker-virtual.artifactory.swisscom.com/mixer
- name: pilot
  newName: cet-docker-virtual.artifactory.swisscom.com/pilot
- name: cet-docker-virtual.artifactory.swisscom.com/busybox
  newName: cet-docker-virtual.artifactory.swisscom.com/cet-docker-virtual.artifactory.swisscom.com/busybox
  newTag: 1.30.1
- name: citadel
  newName: cet-docker-virtual.artifactory.swisscom.com/citadel
- name: servicegraph
  newName: cet-docker-virtual.artifactory.swisscom.com/servicegraph
- name: sidecar_injector
  newName: cet-docker-virtual.artifactory.swisscom.com/sidecar_injector
- name: proxyv2
  newName: cet-docker-virtual.artifactory.swisscom.com/proxyv2
- name: proxy_init
  newName: cet-docker-virtual.artifactory.swisscom.com/proxy_init
- name: docker.io/istio/citadel
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/citadel
  newTag: 1.1.4
- name: docker.io/istio/proxy_init
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/proxy_init
  newTag: 1.1.4
- name: docker.io/istio/kubectl
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/kubectl
  newTag: 1.1.4
- name: docker.io/istio/galley
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/galley
  newTag: 1.1.4
- name: docker.io/istio/proxyv2
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/proxyv2
  newTag: 1.1.4
- name: grafana/grafana
  newName: cet-docker-virtual.artifactory.swisscom.com/grafana/grafana
  newTag: 6.0.2
- name: docker.io/kiali/kiali
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/kiali/kiali
  newTag: v0.16
- name: docker.io/istio/mixer
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/mixer
  newTag: 1.1.4
- name: busybox
  newName: cet-docker-virtual.artifactory.swisscom.com/busybox
  newTag: 1.30.1
- name: docker.io/prom/prometheus
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/prom/prometheus
  newTag: v2.3.1
- name: docker.io/istio/sidecar_injector
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/sidecar_injector
  newTag: 1.1.4
- name: docker.io/jaegertracing/all-in-one
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/jaegertracing/all-in-one
  newTag: "1.9"
- name: docker.io/istio/proxy_init
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/proxy_init
  newTag: 0.7.1
- name: docker.io/istio/proxy_debug
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/proxy_debug
  newTag: 1.1.4
- name: istio/examples-bookinfo-details-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-details-v1
  newTag: 1.10.1
- name: istio/examples-bookinfo-ratings-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-ratings-v1
  newTag: 1.10.1
- name: istio/examples-bookinfo-reviews-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-reviews-v1
  newTag: 1.10.1
- name: istio/examples-bookinfo-reviews-v2
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-reviews-v2
  newTag: 1.10.1
- name: istio/examples-bookinfo-reviews-v3
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-reviews-v3
  newTag: 1.10.1
- name: istio/examples-bookinfo-productpage-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-productpage-v1
  newTag: 1.10.1
- name: istio/examples-bookinfo-mongodb
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-mongodb
  newTag: 1.10.1
- name: istio/examples-bookinfo-details-v2
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-details-v2
  newTag: 1.10.1
- name: istio/examples-bookinfo-mysqldb
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-mysqldb
  newTag: 1.10.1
- name: istio/examples-bookinfo-ratings-v2
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-ratings-v2
  newTag: 1.10.1
- name: istio/examples-bookinfo-ratings-v2
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-ratings-v2
  newTag: 1.10.0
- name: istio/examples-helloworld-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-helloworld-v1
- name: k8s.gcr.io/busybox
  newName: cet-docker-virtual.artifactory.swisscom.com/k8s.gcr.io/busybox
- name: docker.io/istio/health
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/istio/health
  newTag: example
- name: istio/examples-helloworld-v2
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-helloworld-v2
- name: docker.io/kennethreitz/httpbin
  newName: cet-docker-virtual.artifactory.swisscom.com/docker.io/kennethreitz/httpbin
- name: fortio/fortio
  newName: cet-docker-virtual.artifactory.swisscom.com/fortio/fortio
  newTag: latest_release
- name: ymqytw/nginxhttps
  newName: cet-docker-virtual.artifactory.swisscom.com/ymqytw/nginxhttps
  newTag: "1.5"
- name: istio/examples-bookinfo-ratings-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-ratings-v1
  newTag: 0.2.3
- name: istio/examples-bookinfo-reviews-v2
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-reviews-v2
  newTag: 0.2.3
- name: istio/examples-bookinfo-details-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-details-v1
  newTag: 0.2.3
- name: istio/examples-bookinfo-reviews-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-reviews-v1
  newTag: 0.2.3
- name: istio/examples-bookinfo-productpage-v1
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/examples-bookinfo-productpage-v1
  newTag: 0.2.3
- name: pstauffer/curl
  newName: cet-docker-virtual.artifactory.swisscom.com/pstauffer/curl
- name: istio/tcp-echo-server
  newName: cet-docker-virtual.artifactory.swisscom.com/istio/tcp-echo-server
  newTag: "1.1"
- name: hiroakis/tornado-websocket-example
  newName: cet-docker-virtual.artifactory.swisscom.com/hiroakis/tornado-websocket-example
